Adicionado algoritmo Bubble Sort: Issue #39
devs-javagirl/java-trainning pull request #53
Opened 2023-10-04 19:32 UTC by Pris-c

Resolução da issue: Algoritmos - Bubble sort #39 .

2023-10-11 02:50 UTC, Kamilahsantos requested changes
conseguiria colocar esses arquivos .idea dentro de um arquivo .gitignore, que ai o git não inclui esses arquivos que não fazem parte do desenvolvimento =)

2023-10-11 12:51 UTC, Pris-c commented
Pronto, Kamila. Criei o gitignore com os arquivos desnecessários.

2023-10-18 00:04 UTC, gleiceellen approved these changes

2023-10-21 12:14 UTC, Pris-c commented
Oi ! Ainda falta alguma alteração para ser mergeado?

2023-10-25 00:57 UTC, Kamilahsantos commented
> Oi ! Ainda falta alguma alteração para ser mergeado?

oii tudo certo, vou mergear agora =)

2023-10-25 00:57 UTC, merged